export const AUTHOR_LIST_REQUEST = "AUTHOR_LIST_REQUEST";
export const AUTHOR_LIST_SUCCESS = "AUTHOR_LIST_SUCCESS";
export const AUTHOR_LIST_FAIL = "AUTHOR_LIST_FAIL";

export const AUTHOR_POPULAR_REQUEST = "AUTHOR_POPULAR_REQUEST";
export const AUTHOR_POPULAR_SUCCESS = "AUTHOR_POPULAR_SUCCESS";
export const AUTHOR_POPULAR_FAIL = "AUTHOR_POPULAR_FAIL";

export const AUTHOR_DETAILS_REQUEST = "AUTHOR_DETAILS_REQUEST";
export const AUTHOR_DETAILS_SUCCESS = "AUTHOR_DETAILS_SUCCESS";
export const AUTHOR_DETAILS_FAIL = "AUTHOR_DETAILS_FAIL";
