export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";

export const BLOG_LATEST_REQUEST = "BLOG_LATEST_REQUEST";
export const BLOG_LATEST_SUCCESS = "BLOG_LATEST_SUCCESS";
export const BLOG_LATEST_FAIL = "BLOG_LATEST_FAIL";

export const BLOG_CATEGORIES_REQUEST = "BLOG_CATEGORIES_REQUEST";
export const BLOG_CATEGORIES_SUCCESS = "BLOG_CATEGORIES_SUCCESS";
export const BLOG_CATEGORIES_FAIL = "BLOG_CATEGORIES_FAIL";

export const BLOG_TAGS_REQUEST = "BLOG_TAGS_REQUEST";
export const BLOG_TAGS_SUCCESS = "BLOG_TAGS_SUCCESS";
export const BLOG_TAGS_FAIL = "BLOG_TAGS_FAIL";
