export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
export const BOOK_DETAILS_RESET = "BOOK_DETAILS_RESET";

export const BOOK_GENRE_REQUEST = "BOOK_GENRE_REQUEST";
export const BOOK_GENRE_SUCCESS = "BOOK_GENRE_SUCCESS";
export const BOOK_GENRE_FAIL = "BOOK_GENRE_FAIL";

export const BOOK_AUTHOR_REQUEST = "BOOK_AUTHOR_REQUEST";
export const BOOK_AUTHOR_SUCCESS = "BOOK_AUTHOR_SUCCESS";
export const BOOK_AUTHOR_FAIL = "BOOK_AUTHOR_FAIL";

export const BOOK_FORMAT_REQUEST = "BOOK_FORMAT_REQUEST";
export const BOOK_FORMAT_SUCCESS = "BOOK_FORMAT_SUCCESS";
export const BOOK_FORMAT_FAIL = "BOOK_FORMAT_FAIL";

export const BOOK_PUBLISHER_REQUEST = "BOOK_PUBLISHER_REQUEST";
export const BOOK_PUBLISHER_SUCCESS = "BOOK_PUBLISHER_SUCCESS";
export const BOOK_PUBLISHER_FAIL = "BOOK_PUBLISHER_FAIL";

export const BOOK_LATEST_RELEASE_REQUEST = "BOOK_LATEST_RELEASE_REQUEST";
export const BOOK_LATEST_RELEASE_SUCCESS = "BOOK_LATEST_RELEASE_SUCCESS";
export const BOOK_LATEST_RELEASE_FAIL = "BOOK_LATEST_RELEASE_FAIL";

export const BOOK_POPULAR_REQUEST = "BOOK_POPULAR_REQUEST";
export const BOOK_POPULAR_SUCCESS = "BOOK_POPULAR_SUCCESS";
export const BOOK_POPULAR_FAIL = "BOOK_POPULAR_FAIL";

export const BOOK_FEATURED_REQUEST = "BOOK_FEATURED_REQUEST";
export const BOOK_FEATURED_SUCCESS = "BOOK_FEATURED_SUCCESS";
export const BOOK_FEATURED_FAIL = "BOOK_FEATURED_FAIL";

export const BOOK_SALE_REQUEST = "BOOK_SALE_REQUEST";
export const BOOK_SALE_SUCCESS = "BOOK_SALE_SUCCESS";
export const BOOK_SALE_FAIL = "BOOK_SALE_FAIL";

export const BOOK_WITH_ORDERS_REQUEST = "BOOK_WITH_ORDERS_REQUEST";
export const BOOK_WITH_ORDERS_SUCCESS = "BOOK_WITH_ORDERS_SUCCESS";
export const BOOK_WITH_ORDERS_FAIL = "BOOK_WITH_ORDERS_FAIL";
export const BOOK_WITH_ORDERS_RESET = "BOOK_WITH_ORDERS_RESET";

export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";
export const BOOK_CREATE_RESET = "BOOK_CREATE_RESET";

export const BOOK_UPDATE_REQUEST = "BOOK_UPDATE_REQUEST";
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";
export const BOOK_UPDATE_RESET = "BOOK_UPDATE_RESET";

export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";
export const BOOK_DELETE_RESET = "BOOK_DELETE_RESET";

export const BOOK_RATINGS_REQUEST = "BOOK_RATINGS_REQUEST";
export const BOOK_RATINGS_SUCCESS = "BOOK_RATINGS_SUCCESS";
export const BOOK_RATINGS_FAIL = "BOOK_RATINGS_FAIL";

export const BOOK_RATINGS_DISTRIBUTION_REQUEST =
  "BOOK_RATINGS_DISTRIBUTION_REQUEST";
export const BOOK_RATINGS_DISTRIBUTION_SUCCESS =
  "BOOK_RATINGS_DISTRIBUTION_SUCCESS";
export const BOOK_RATINGS_DISTRIBUTION_FAIL = "BOOK_RATINGS_DISTRIBUTION_FAIL";

export const BOOK_CREATE_RATINGS_REQUEST = "BOOK_CREATE_RATINGS_REQUEST";
export const BOOK_CREATE_RATINGS_SUCCESS = "BOOK_CREATE_RATINGS_SUCCESS";
export const BOOK_CREATE_RATINGS_FAIL = "BOOK_CREATE_RATINGS_FAIL";

export const BOOK_DELETE_RATINGS_REQUEST = "BOOK_DELETE_RATINGS_REQUEST";
export const BOOK_DELETE_RATINGS_SUCCESS = "BOOK_DELETE_RATINGS_SUCCESS";
export const BOOK_DELETE_RATINGS_FAIL = "BOOK_DELETE_RATINGS_FAIL";
