export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const BOOK_GENRE_REQUEST = "BOOK_GENRE_REQUEST";
export const BOOK_GENRE_SUCCESS = "BOOK_GENRE_SUCCESS";
export const BOOK_GENRE_FAIL = "BOOK_GENRE_FAIL";

export const BOOK_AUTHOR_REQUEST = "BOOK_AUTHOR_REQUEST";
export const BOOK_AUTHOR_SUCCESS = "BOOK_AUTHOR_SUCCESS";
export const BOOK_AUTHOR_FAIL = "BOOK_AUTHOR_FAIL";

export const BOOK_FORMAT_REQUEST = "BOOK_FORMAT_REQUEST";
export const BOOK_FORMAT_SUCCESS = "BOOK_FORMAT_SUCCESS";
export const BOOK_FORMAT_FAIL = "BOOK_FORMAT_FAIL";
